# Generated by Django 5.2.9 on 2026-01-26 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_min',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('ETS', 'Holt-Winters ETS'), ('BASELINE', 'Baseline estacional')], default='ETS', max_length=30)),
                ('forecast_date', models.DateField()),
                ('forecast_value', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.product')),
            ],
            options={
                'ordering': ['-generated_at', '-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='ForecastMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('method', models.CharField(choices=[('ETS', 'Holt-Winters ETS'), ('BASELINE', 'Baseline estacional')], max_length=30)),
                ('mae', models.FloatField()),
                ('rmse', models.FloatField()),
                ('mape', models.FloatField()),
                ('prediction_time_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
