# Generated by Django 6.0.1 on 2026-02-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_forecastmetric_product_delete_forecast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sale',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='serial_number',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='tpotal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
