# Generated by Django 6.0.1 on 2026-02-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_sale_created_at_remove_sale_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='tpotal_price',
            new_name='total_price',
        ),
    ]
