# Generated by Django 6.0.1 on 2026-05-09 19:07

from django.db import migrations, models


def populate_sale_quantities(apps, schema_editor):
    Sale = apps.get_model("inventory", "Sale")
    for sale in Sale.objects.select_related("product").all():
        price = sale.product.price if sale.product else 0
        if price:
            quantity = int(round(float((sale.total_price or 0) / price)))
        else:
            quantity = 1
        sale.quantity = max(quantity, 1)
        sale.save(update_fields=["quantity"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_convert_eur_to_pen_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(populate_sale_quantities, migrations.RunPython.noop),
    ]
